---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.3.0

executors:
  infra-image:
    docker:
      - image: twdps/di-circleci-infra-image:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    shell: secrethub run -- /bin/sh -eo pipefail
      
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:
  deploy-istio:
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: ""
    steps:
      - run:
          name: pull kubeconfig
          command: |
            ls -la
            mkdir ~/.kube
            SECRETHUB_VAR_ENV=<< parameters.cluster >> secrethub inject -i tpl/kubeconfig.tpl -o ~/.kube/config
      - run:
          name: deploy istio with cluster specific values
          command: bash tpl/deploy_istio.sh << parameters.cluster >>
      - run:
          name: deploy external dns
          command: bash tpl/deploy_external_dns.sh << parameters.cluster >>
      - run:
          name: test servicemesh deployment
          command: CLUSTER=<< parameters.cluster >> bats test/platform_servicemesh.bats
      - run:
          name: deploy httpbin and validate
          command: bash tpl/deploy_httpbin.sh << parameters.cluster >>
      - run:
          name: test httpbin traffic
          command: CLUSTER=<< parameters.cluster >> bats test/platform_httpbin.bats
      - run:
          name: deploy monitoring traffic management
          command: bash tpl/deploy_monitoring_traffic_management.sh << parameters.cluster >>
      - run:
          name: deploy api traffic management for di-dev
          command: bash tpl/deploy_api_traffic_management.sh << parameters.cluster >> di-dev
      - run:
          name: deploy api traffic management for di-staging
          command: bash tpl/deploy_api_traffic_management.sh << parameters.cluster >> di-staging
      - run:
          name: test traffic management
          command: CLUSTER=<< parameters.cluster >> bats test/platform_traffic_management.bats

jobs:
  deploy-servicemesh:
    executor: infra-image
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: ""
    steps:
      - checkout
      - setup_remote_docker
      - deploy-istio:
          cluster: << parameters.cluster >>

workflows:
  version: 2

  poc-platform-servicemesh-pipeline:
    jobs:
      - terraform/plan:
          name: sandbox-change-plan
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          filters: *on-push-master

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: sandbox-change-apply
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          requires:
            - approve-sandbox-changes
          filters: *on-push-master

      - deploy-servicemesh:
          name: deploy-sandbox-servicemesh
          context: dps-va-di
          cluster: sandbox
          requires:
            - sandbox-change-apply
          filters: *on-push-master
      
      - deploy-servicemesh:
          name: deploy-preview-servicemesh
          context: dps-va-di
          cluster: preview
          filters: *on-tag-master
